spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    open-in-view: true
server:
  port: 8081
